### ISSUE TITLE
Cross-platform Build Instructions

### ISSUE THREAD

**Issue by codespook** [vanila-io/wireflow#1]
Can development be done in a windows environment? If not then, will working in a VM be feasible?

**Comment by shtefcs** [comment]
I think it should be, since Meteor support Windows platform. What you think @entrptaher  ?

**Comment by entrptaher** [comment]
Yes development can be done in windows. 
We'll put some windows setup instructions soon.

**Comment by jankapunkt** [comment]
Please also add build instructions for OSX.

**Comment by entrptaher** [comment]
I think OSX and Linux will have same build instructions. We will see.

**Comment by jankapunkt** [comment]
I was just concerned because of this REAMDE part:
`sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev libjpeg8-dev libpango1.0-dev build-essential g++`
which is only working for Debian based Linux Dsitributions.

**Comment by entrptaher** [comment]
Probably this is what we need instead of that.
`brew install pkg-config cairo libpng jpeg giflib`

**Comment by entrptaher** [comment]
@nikw92 can you try the latest readme file and see if you manage to install wireflow on windows?

**Comment by entrptaher** [comment]
@jankapunkt can you confirm that if you use the packages below, then you can run wireflow on your local?
```
brew install pkg-config cairo libpng jpeg giflib
```

**Comment by mikkelking** [comment]
I used this brew install list, I only needed giflib (the others were already installed).
Slingshot caused some problems:

```
W20171129-20:24:51.960(11)? (STDERR)       throw error;
W20171129-20:24:51.960(11)? (STDERR)       ^
W20171129-20:24:52.005(11)? (STDERR) Error: Match error: Expected string, got undefined in field bucket
W20171129-20:24:52.005(11)? (STDERR)     at exports.check (packages/check.js:55:15)
W20171129-20:24:52.005(11)? (STDERR)     at new Slingshot.Directive (packages/edgee_slingshot.js:325:3)
W20171129-20:24:52.006(11)? (STDERR)     at Object.Slingshot.createDirective (packages/edgee_slingshot.js:295:5)
W20171129-20:24:52.006(11)? (STDERR)     at Slingshot.js (imports/startup/server/Slingshot.js:5:11)
W20171129-20:24:52.006(11)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20171129-20:24:52.006(11)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20171129-20:24:52.006(11)? (STDERR)     at index.js (imports/startup/server/index.js:1:229)
W20171129-20:24:52.006(11)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20171129-20:24:52.007(11)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20171129-20:24:52.007(11)? (STDERR)     at main.js (server/main.js:1:14)
```
I am thinking I need a meteor settings file  to point to an S3 bucket? Now I see it, I'll have a go at that. 
I commented the slingshot import, and the app runs ok, I can draw some things. So far so good

**Comment by mikkelking** [comment]
By using the settings file the problem goes away. You should put a reference into the getting started guide about the need for a `--settings settings.json` parameter when running meteor

**Comment by entrptaher** [comment]
@mikkelking I did say you need to write `meteor yarn start`

**Comment by mikkelking** [comment]
@entrptaher  Yes you did, and as I don't use yarn I ignored that. For the sake of completeness it would be worth mentioning that you can run it with the meteor command. Typically i set environment variables like this:

```
DEBUG=tm:* MONGO_URL=mongodb://server... meteor --port 3050 --settings dev.settings.json
```

It doesn't hurt to cover all options :)

**Comment by entrptaher** [comment]
Alright, I will add that :)

**Comment by badis** [comment]
@entrptaher 
I think it's also good to add npm commands also:

```
meteor npm install
meteor npm start
meteor npm test
```

For people not familiar with yarn although there is no difference between them.

**Comment by xet7** [comment]
I added pull request that makes possible running wireflow even when AWS S3 credentials are not defined, and some other upgrades etc. https://github.com/vanila-io/wireflow/pull/31
