### ISSUE TITLE
'Chart search' appears to return many duplicate results

### ISSUE THREAD

**Issue by jimsmart** [vanila-io/wireflow#10]
Steps to reproduce:

1. Go to https://wireflow.co/
2. Click 'start designing'
3. Click 'see charts'
4. In the search field, type 'sign' or 'blog'
5. The results list appears to contain many duplicates

Expected results: if there are only four items matching my search, I expect to see a list of only those four items. If these items are not actually duplicates, then I expect to be able to differentiate them from one another.

Thanks!

**Comment by shtefcs** [comment]
Hey @jimsmart  yeah, that is old known bug and someone will take care of it soon or later. The next task is to update dependencies, so everything will be up to date.
