### ISSUE TITLE
Upgrade from react-komposer to withTracker

### ISSUE THREAD

**Issue by tomscholz** [vanila-io/wireflow#12]

**Comment by shtefcs** [comment]
Thanks for the issue @tomscholz . If you are able to do it, feel free to pick it up and submit PR.

**Comment by tomscholz** [comment]
I will try to look into it this weekend💃✌🦄

**Comment by shtefcs** [comment]
hehe, that is nice Tom, lets see 🦉  ☺️

**Comment by badis** [comment]
Hi gays,

I have done a lot on this, please review this PR ( https://github.com/vanila-io/wireflow/pull/14)  and let me know what you think.

**Comment by shtefcs** [comment]
That a great @badis ^^

**Comment by badis** [comment]
Hi @tomscholz 

Take a look at this : https://github.com/vanila-io/wireflow/pull/16
I have changed composeWithTracker with withTracker from react-meteor-data.
I think react-meteor-data is enough and we no longer need to keep react-komposer.
Please let me know what do you think and correct me if I am missing something.
