### ISSUE TITLE
Update Meteor Version to 1.6 and Packages to the latest compatible/stable

### ISSUE THREAD

**Issue by jankapunkt** [vanila-io/wireflow#2]
I think a good first milestone would be to make this project run using up to date versions of Meteor and the packages. Also the NPM packages require a version update.

**Comment by shtefcs** [comment]
Yes @jankapunkt  that is what I think as well. Among the good roadmap and docs, the should be first step in future development.

**Comment by entrptaher** [comment]
There are some packages that are obsolate and won't compile under node v8.8.1. We need to remove those packages. Such as 
- contextify which is an indirect dependency of fabric.js,
- the dev dependencies like faker and chimp.
