### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by entrptaher** [vanila-io/wireflow#23]
This is one of the major issues we will be working on.

1. Admin database exposed at `/admin/users`
2. Websocket is unauthenticated

The reason is, this was a prototype and got hunted on producthunt unfortunatly. 

Action:
- Take down wireflow for now,
- Fix these problems before moving on to next version.

**Comment by xet7** [comment]
@entrptaher 

According to `npm audit`, after Meteor 1.8.1 upgrades at https://github.com/vanila-io/wireflow/pull/31 remaining issue is materialize-css that could be low severity one, it seems to not yet have fix or replacement available, at lease I did not find replacement version yet.

There could be some other issues that `npm audit` does not show at all.
