### ISSUE TITLE
Request for docker image

### ISSUE THREAD

**Issue by bluenevus** [vanila-io/wireflow#26]
Humble request for a docker image

**Comment by entrptaher** [comment]
The current version is pretty old, but hold on, let me create one, since it will also improve development setup.

**Comment by bluenevus** [comment]
Thanks!!!

**Comment by bluenevus** [comment]
any luck on that docker image?

**Comment by entrptaher** [comment]
Clone the repo and use the following docker file, all preconfigured just as explained on the linux setup. :D

Here are the steps.

Create a `Dockerfile`:
```
FROM node:8

# Install all dependencies
RUN apt-get update
RUN apt-get install -y curl build-essential g++ libcairo2-dev libjpeg-dev libgif-dev libpango1.0-dev libcairo2-dev libjpeg62-turbo-dev libpango1.0-dev libgif-dev build-essential g++

# Install meteor 1.6
RUN curl https://install.meteor.com/?release=1.6 | /bin/sh
RUN meteor npm install -g yarn node-gyp

# Install Packages
ADD . /opt/wireflow
WORKDIR /opt/wireflow
RUN meteor yarn --ignore-optional
# The dependencies changed since then
RUN meteor yarn add bufferutil utf-8-validate canvas xmldom --ignore-optional

# Set environment variables 
ENV LC_ALL C
ENV METEOR_ALLOW_SUPERUSER true

# Expose ports
EXPOSE 3000

# Start the app
CMD yarn run start
```

Build it:
```
sudo docker build -t wireflow .
```

Run it:
```
sudo docker run --net=host -it wireflow
```

Here are the drawbacks of this strategy:
- You will get this warning (`Even with METEOR_ALLOW_SUPERUSER ...`), however it's sufficient to run meteor at this point.
- This will run as a development version, not a production version.

**Comment by entrptaher** [comment]
Feel free to reopen if this does not solve.
