### ISSUE TITLE
Spotted a typo, I think

### ISSUE THREAD

**Issue by simplytammy** [vanila-io/wireflow#32]
![Screenshot_2019-11-06 Wireflow - Free Wire User Flow Tool](https://user-images.githubusercontent.com/36845308/68279724-52962780-0074-11ea-8bb4-3f2ea180db6f.png)
I do not know if it is a typo or not, but on the home page of the official website you spelt **open** **source** as **open sorrce**.

**Comment by shtefcs** [comment]
Hey thanks @simplytammy , I noticed as well, just didn't have time to fix and deploy.
