### ISSUE TITLE
Invalid SSL Certificate

### ISSUE THREAD

**Issue by idevelop** [vanila-io/wireflow#39]
Your SSL certificate seems to be invalid which is causing some app-level issues. 

> Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('https://app.wireflow.co/') with script ('https://app.wireflow.co/service-worker.js'): An SSL certificate error occurred when fetching the script.

I think this might be breaking the autosave functionality.

**Comment by shtefcs** [comment]
Hey, thanks for reporting. I gonna mention @entrptaher to this issue, so he can check it out when have time.

Andrei, have in mind this is an old side project of ours, and we are not much active.

**Comment by idevelop** [comment]
@shtefcs no problem, I absolutely understand and it's up to you if/when you want to act on this issue. 

For the record, I love the approach you're taking with the predefined "UI mockup" blocks instead of freeform shapes/text/etc, and I would pay for this if it had a working autosave and a couple other small feature requests.

**Comment by shtefcs** [comment]
HEhe, thanks for the feedback Andreia, its put a smile on my face when I
hear those kinds of comments.

Wireflow born with idea to being able to simply create wireflows without
using any complex Softwares like Photoshop, illustrator or needs to buy any
kits.

This was a side project, and we never put to much effort in it. But
hopefully one day we can back and fully re-think the app.

-----------------------
Stefan Smiljkovic
Co-Founder & CEO
Vanila.io, Automatio.co
(e): stefan@vanila.io
(p): +381 62 973 4218

**Comment by vanilataher** [comment]
Hello @idevelop thank you for the report. I believe the issue is fixed. Let me know if it's still not the case.
