### ISSUE TITLE
Dragging components does not work in Firefox

### ISSUE THREAD

**Issue by igorvanoostveen** [vanila-io/wireflow#45]
### Observed behavior
When using Firefox, a user tries to drag a component from the component library (on the left hand side of the window), but no component is dragged and a selection area appears in the component library.

### Expected behavior
To be able to drag components from the components library like on other browsers (tested Chrome).

### Details
Observed in Firefox 80.0.1, Firefox 81.0, Firefox Nightly 83.0a1 (2020-09-28).

### Screenshot
![20200929 Firefox - dragging component fails](https://user-images.githubusercontent.com/889586/94526661-1d6b6880-0236-11eb-80e2-bf40c3567ac4.png)

**Comment by igorvanoostveen** [comment]
Duplicate to issue #35

**Comment by nagytech** [comment]
@igorvanoostveen 

This issue has good details about the problem compared to #35.  You probably should have left it open so that it's visible - since then there's been another duplicate created.
