### ISSUE TITLE
Clicking Become a Backer image does not work.

### ISSUE THREAD

**Issue by thgilartlu** [vanila-io/wireflow#48]
![image](https://user-images.githubusercontent.com/71095679/94539160-c6b55d00-023c-11eb-823e-f8bd7c8d8480.png)

Clicking the [Become a backer] correctly links to https://opencollective.com/wireflow#backer
Clicking the image highlighted in the attached redirects to https://opencollective.com/%7B%7Bslug%7D%7D#backers

`<a href="https://opencollective.com/{{slug}}#backers" target="_blank"><img src="https://opencollective.com/wireflow/backers.svg?width=890"></a>`

**Comment by jonaed1230** [comment]
This issue is fixed in this commit https://github.com/vanila-io/wireflow/commit/4b97b90b927cb410126e040ce67a86588bf946ab
