### ISSUE TITLE
High pitched sound on homepage

### ISSUE THREAD

**Issue by pranavmangal** [vanila-io/wireflow#50]
A rather terrible high pitched sound clip is played on https://wireflow.co upon page load.

Unless the intention is to scare away potential users, I think it's best to get rid of it. 
[People on Hacker News seem to agree](https://news.ycombinator.com/item?id=24625041).

**Comment by WarenGonzaga** [comment]
@pranavmangal agree... I look around where to find that sound and I found out that it is on page load via the site. It's kind of annoying in my opinion.

**Comment by entrptaher** [comment]
Thank you for bringing this. This and few other issues about the homepage will be handled in https://github.com/vanila-io/wireflow-homepage.

**Comment by WarenGonzaga** [comment]
@entrptaher I created an issue on that repo.

**Comment by jonaed1230** [comment]
This issue is fixed and merged in here [vanila-io/wireflow-homepage pull request #7](https://github.com/vanila-io/wireflow-homepage/pull/7)
