### ISSUE TITLE
Reseting canvas removes it

### ISSUE THREAD

**Issue by entrptaher** [vanila-io/wireflow#6]
First we saw a white canvas background.
![screenshot from 2017-12-08 20-24-04](https://user-images.githubusercontent.com/8284972/33769883-f6df753e-dc55-11e7-83c0-1ccf44290aae.png)

And then we cleared the canvas.
![screenshot from 2017-12-08 20-24-15](https://user-images.githubusercontent.com/8284972/33769886-f93f9f16-dc55-11e7-88b7-cbe7a97e011c.png)

And we see the while background is gone completely. 
![screenshot from 2017-12-08 20-24-31](https://user-images.githubusercontent.com/8284972/33769888-fcb9b5be-dc55-11e7-96c0-d98f2c83d01f.png)

Creating anything will not have a white background. It should be white by default.

**Comment by shtefcs** [comment]
What do you mean @entrptaher  ?

**Comment by entrptaher** [comment]
I'll update the main post with in depth details.

**Comment by entrptaher** [comment]
Information updated.

**Comment by shtefcs** [comment]
Oh that, yeah I remember that bug from the start. Will that be fixed with the React upgrade and other PR's u guys did ?

**Comment by entrptaher** [comment]
No, it's a separate issue with logics I think. Like the logic for those features are incomplete.

**Comment by shtefcs** [comment]
Okay, got it.
