### ISSUE TITLE
adding new svgs

### ISSUE THREAD

**Issue by julientaq** [vanila-io/wireflow#9]
Hey there! Thanks for the open source and the nice tool you built.

We're trying to set it up and see if it can be useful for creating workflow from multiple design team regarding the same tool.

What would be the best way to add new charts to the app? 
For now we can replace your svg, but what if we want to get deeper into customisation?

**Comment by shtefcs** [comment]
@julientaq  glad you find it useful. 

I am still thinking if we create a new repo for SVG's to be easier for people to access it, modify and add new. 

Do you thinking adding the new SVG's but to contain same style, just different screens ?

Peace,

**Comment by shtefcs** [comment]
Also, are you looking for .AI (Illustrator) source file for graphics, so you can continue edit from there ?

**Comment by julientaq** [comment]
> Do you thinking adding the new SVG's but to contain same style, just different screens ?

I'm thinking about completely new svg: content, styles, colors… to be more accurate with the brand and with the features of each part of screen for the apps we're building and gives access to developers, designers and who ever we need to come and comment on the workflow, while being outside of designers tools. So i'm thinking about adding smaller component (input, button, text block) and go from here. (it may be a hacky way of thinking about your tool, but to be honest, there is nothing in open source that let us work this way, so i want to try it and see if it can work).

> Also, are you looking for .AI (Illustrator) source file for graphics, so you can continue edit from there ?

I don't think that's a good idea for multiple reasons: 
- having multiple formats would create confusion and more work to find/declare the source of truth, specially if you want to let designer create assets on the fly and put in on the repo;
- i'm happy with the idea of keeping proprietary format files outside of open source project/tools, especially when Illustrator can work with svg with no problem;
- it's easier to have broad changes in svg using only css, and even put that css file somewhere else and just make the change there (colors for example)

oh, and i agree with you signature :D

**Comment by shtefcs** [comment]
@julientaq  Well, I was thinking about that, and that is one of the features to be done. Feature where users can upload/import their own graphics and manipulate them like the current one.

The issue will be open so someone can pick it up and work on it. You your crew if you have some work done, feel free to submit PR.
